backend:
  name: github
  repo: pedrobrnpng/inej_portfolio
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/images
public_folder: img
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "data/projects"
    media_folder: public/images
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Type"
        name: "type"
        widget: "string"
      - label: "Colaborators"
        name: "colaborators"
        widget: "list"
      - label: "Sound"
        name: "sound"
        widget: "list"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "VideoUrl"
        name: "videoUrl"
        widget: "string"