backend:
  name: git-gateway
  repo: pedrobrnpng/inej_portfolio
  branch: main # Branch to update (optional; defaults to master)
  # name: test-repo
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: img
collections:
  - name: "about"
    label: "About"
    files: 
      - label: About
        name: about
        file: "data/aboutme/itsme.md"
        media_folder: "public/images"  
        fields: 
          - label: "Image"
            name: "img"
            widget: "string"
          - label: "Description"
            name: "body"
            widget: "markdown"
  - name: "portfolio"
    label: "Portfolio"
    folder: "data/projects"
    media_folder: public/images
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Type"
        name: "type"
        widget: "string"
      - label: "Colaborators"
        name: "colaborators"
        widget: "string"
        required: false
      - label: "Sound"
        name: "sound"
        widget: "string"
        required: false
      - label: "Image"
        name: "img"
        widget: "image"
        required: false
      - label: "VideoUrl"
        name: "videoUrl"
        widget: "string"
        required: false
      - label: "Selected?"
        name: "selected"
        widget: "boolean"
      - label: "Description"
        name: "body"
        widget: "markdown"